#+TITLE:  Build Generator
#+AUTHOR: Jan Moringen
#+EMAIL:  jmoringe@techfak.uni-bielefeld.de

#+LINK: jenkins   https://jenkins.io/
#+LINK: sbcl      http://sbcl.org
#+LINK: quicklisp https://www.quicklisp.org/beta/

#+ATTR_HTML: :alt "build status image" :title Build Status :align right
[[https://travis-ci.org/RDTK/generator][https://travis-ci.org/RDTK/generator.svg]]

* TODO Introduction

  The build generator is a program for generating [[jenkins][Jenkins]] jobs (and other things) from declarative recipes describing software projects, software systems (and other things).

* Dependencies

  + Common Lisp Implementation :: At the moment, the code is almost but not quite portable and can only be used with the [[sbcl][SBCL]] implementation of Common Lisp.

  + System Libraries :: For secure communication with the Jenkins server as well as archive retrieval via HTTPS, the build generator relies on the OpenSSL library, specifically =libssl.so.*=.
       In Debian-derived systems, the =openssl= package provides this library.

  + Lisp dependencies :: The following Lisp dependencies cannot be installed automatically via [[quicklisp][Quicklisp]], yet:

       + The [[https://github.com/scymtym/model.transform.trace][model.transform.trace]] project

       + The [[https://github.com/scymtym/language.yaml][language.yaml]] project

       + The [[https://github.com/scymtym/text.source-location][text.source-location]] project

       + The [[https://code.cor-lab.org/projects/rosetta][rosetta]] project

         + The [[https://code.cor-lab.org/projects/rosetta][rosetta-project]] project

* Building

  + Within SBCL ::

    #+BEGIN_SRC lisp
      (asdf:make :jenkins.project.commandline-interface)
    #+END_SRC

  + On the commandline ::

    #+BEGIN_SRC bash
      sbcl --no-userinit --load quicklisp/setup.lisp --eval '(asdf:make :jenkins.project.commandline-interface)'
    #+END_SRC

  Both variants should produce a binary named =build-generator= in the project root directory.

* Contributing

  If you want to contribute to this project, please

  + Submit your intended changes as coherent pull requests.

  + Rebase onto the master branch and squash any fixups and corrections.

  + Make sure the unit tests pass.

* Acknowledgments

  The development of this software has been supported as follows:

  + The development of this software was supported by CoR-Lab, Research Institute for Cognition and Robotics Bielefeld University.

  + This work was supported by the Cluster of Excellence Cognitive Interaction Technology ‘CITEC’ (EXC 277) at Bielefeld University, which is funded by the German Research Foundation (DFG).
