(mapc (lambda+ ((input expected))
        (assert (equal (esrap:parse 'expr input) expected)))
      '((""           nil)
        ("foo"        ("foo"))
        ("foo$bar"    ("foo$bar"))
        ("foo{bar"    ("foo{bar"))
        ("foo}bar"    ("foo}bar"))

        ("${a}"       ((:ref ("a"))))
        ("${a|}"      ((:ref ("a") :default nil)))
        ("${a|b}"     ((:ref ("a") :default "b")))
        ("${a|{b}}"   ((:ref ("a") :default "{b") "}"))
        ("${a|${b}}"  ((:ref ("a") :default (:ref ("b")))))
        ("${${a}}"    ((:ref ((:ref ("a"))))))
        ("@{a}"       ((:ref/list ("a"))))
        ("@{a|}"      ((:ref/list ("a") :default nil)))
        ("@{a|b}"     ((:ref/list ("a") :default "b")))
        ("@{a|{b}}"   ((:ref/list ("a") :default "{b") "}"))
        ("@{a|${b}}"  ((:ref/list ("a") :default (:ref ("b")))))
        ("@{a|a${b}}" ((:ref/list ("a") :default ("a" (:ref ("b"))))))
        ("@{@{a}}"    ((:ref/list ((:ref/list ("a"))))))

        ("foo${a}"    ("foo" (:ref ("a"))))))
